'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LocalizationEditor

 '''<summary>
 '''plhLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plhLocales As Global.System.Web.UI.WebControls.PlaceHolder

 '''<summary>
 '''pnlLocaleRequest control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlLocaleRequest As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''pnlCorePackages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlCorePackages As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''dlCorePackages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlCorePackages As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''pnlPackages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlPackages As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''dlPackages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlPackages As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''dlObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlObjects As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''cmdUploadPack control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUploadPack As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdManageObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManageObjects As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdManagePermissions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManagePermissions As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdManagePartners control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManagePartners As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdClearCaches control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdClearCaches As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdCube control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdCube As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdService control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdService As Global.DotNetNuke.UI.WebControls.CommandButton
End Class
