'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

 '''<summary>
 '''lblOwner control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblOwner As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''plOwnerName control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plOwnerName As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtOwnerName control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtOwnerName As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plOwnerOrganization control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plOwnerOrganization As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtOwnerOrganization control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtOwnerOrganization As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plOwnerEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plOwnerEmail As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtOwnerEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtOwnerEmail As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plOwnerUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plOwnerUrl As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtOwnerUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtOwnerUrl As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblLicense control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblLicense As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''plLicense control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plLicense As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtLicense control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtLicense As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plAttribution control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plAttribution As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtAttribution control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtAttribution As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblOther control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblOther As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''plCachePacks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plCachePacks As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkCachePacks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkCachePacks As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''plAllowDirectDownload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plAllowDirectDownload As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowDirectDownload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowDirectDownload As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''plAllowDataExtract control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plAllowDataExtract As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowDataExtract control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowDataExtract As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''plKeepStatistics control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plKeepStatistics As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkKeepStatistics control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkKeepStatistics As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''plModuleKey control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plModuleKey As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtModuleKey control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtModuleKey As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plAutoImportObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plAutoImportObjects As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAutoImportObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAutoImportObjects As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''plWhiteSpaceSignificant control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plWhiteSpaceSignificant As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkWhiteSpaceSignificant control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkWhiteSpaceSignificant As Global.System.Web.UI.WebControls.CheckBox
End Class
