'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class LocalizationEditor

 '''<summary>
 '''plObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plObjects As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddObjects As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plSourceLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plSourceLocale As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddSourceLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddSourceLocale As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plLocales As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddLocales As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plEditorTypes control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plEditorTypes As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddEditorTypes control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddEditorTypes As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plCopyToEmpty control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plCopyToEmpty As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkCopyToEmpty control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkCopyToEmpty As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''cmdEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdEdit As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdVerify control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdVerify As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdLangPack control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdLangPack As Global.System.Web.UI.WebControls.LinkButton
End Class
