'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Settings

 '''<summary>
 '''plLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plLocales As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkLocales As Global.System.Web.UI.WebControls.CheckBoxList

 '''<summary>
 '''plObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plObjects As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkObjects As Global.System.Web.UI.WebControls.CheckBoxList

 '''<summary>
 '''plRemoveBlanksFromFile control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plRemoveBlanksFromFile As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkRemoveBlanksFromFile control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkRemoveBlanksFromFile As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''plAddNewEntriesAsBlank control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plAddNewEntriesAsBlank As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAddNewEntriesAsBlank control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAddNewEntriesAsBlank As Global.System.Web.UI.WebControls.CheckBox
End Class
