'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class LocalizationEditor

 '''<summary>
 '''pnlEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''dlObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlObjects As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''lbManageObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lbManageObjects As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lbManagePermissions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lbManagePermissions As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lbClearCaches control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lbClearCaches As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''hlCube control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents hlCube As Global.System.Web.UI.WebControls.HyperLink
End Class
