'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LocalizationEditor

 '''<summary>
 '''pnlEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''dlObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlObjects As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''cmdUploadPack control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUploadPack As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdManageObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManageObjects As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdManagePermissions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManagePermissions As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdManagePartners control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManagePartners As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''cmdClearCaches control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdClearCaches As Global.DotNetNuke.UI.WebControls.CommandButton

 '''<summary>
 '''hlCube control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents hlCube As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''imgCube control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents imgCube As Global.System.Web.UI.WebControls.Image
End Class
