'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ManageObjects

 '''<summary>
 '''lblImportObject control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblImportObject As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblPackageFile control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPackageFile As Global.System.Web.UI.UserControl

 '''<summary>
 '''ctlUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlUpload As Global.System.Web.UI.WebControls.FileUpload

 '''<summary>
 '''lbImportPackage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lbImportPackage As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lblInstalledObject control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblInstalledObject As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddlInstalledObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddlInstalledObjects As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lbImportInstalledObject control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lbImportInstalledObject As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lblUploadError control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblUploadError As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''cmdReturn control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lblCurrentObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCurrentObjects As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''dlTranslateObjects control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlTranslateObjects As Global.System.Web.UI.WebControls.DataList
End Class
