'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ObjectSummary

 '''<summary>
 '''lblCurrentVersion control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCurrentVersion As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblCurrentVersionLoc control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCurrentVersionLoc As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblNrOfFiles control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblNrOfFiles As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblNrOfItems control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblNrOfItems As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblNrOfChangedTexts control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblNrOfChangedTexts As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblNrOfMissingTranslations control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblNrOfMissingTranslations As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblPercentageComplete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPercentageComplete As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblEdit As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''plSourceLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plSourceLocale As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddSourceLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddSourceLocale As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plVersion control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plVersion As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddVersion control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddVersion As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plSelection control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plSelection As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddSelection control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddSelection As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''cmdEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdEdit As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdDownload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDownload As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''cmdUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''cmdReturn control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.HyperLink
End Class
