'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RequestPack

 '''<summary>
 '''form1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

 '''<summary>
 '''dnnLOGO control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dnnLOGO As Global.System.Web.UI.UserControl

 '''<summary>
 '''pnlMain control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''pnlHeader control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''pnlTranslations control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlTranslations As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblVersion control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''ddVersion control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddVersion As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblTotalTranslations control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTotalTranslations As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''dgLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dgLocales As Global.System.Web.UI.WebControls.DataGrid

 '''<summary>
 '''lblHelp control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblHelp As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''plLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plLocale As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtLocale As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''cmdDownload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDownload As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''regLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents regLocale As Global.System.Web.UI.WebControls.RegularExpressionValidator

 '''<summary>
 '''lblNoResourceFiles control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblNoResourceFiles As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''pnlDisambiguate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlDisambiguate As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''plhDisambiguate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plhDisambiguate As Global.System.Web.UI.WebControls.PlaceHolder

 '''<summary>
 '''lblError control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
End Class
