'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Editor

 '''<summary>
 '''lblContent control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblContent As Global.DotNetNuke.UI.WebControls.DNNLabelEdit

 '''<summary>
 '''tbEIPHTML control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbEIPHTML As Global.DotNetNuke.UI.WebControls.DNNToolBar

 '''<summary>
 '''tbEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbEdit As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbSave control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbSave As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbCancel As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbBold control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbBold As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbItalic control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbItalic As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbUnderline control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbUnderline As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbJustifyLeft control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbJustifyLeft As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbJustifyCenter control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbJustifyCenter As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbJustifyRight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbJustifyRight As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbOrderedList control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbOrderedList As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbUnorderedList control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbUnorderedList As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbOutdent control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbOutdent As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbIndent control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbIndent As Global.DotNetNuke.UI.WebControls.DNNToolBarButton

 '''<summary>
 '''tbCreateLink control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tbCreateLink As Global.DotNetNuke.UI.WebControls.DNNToolBarButton
End Class
