'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DNNEurope.Modules.LocalizationEditor.Controls

	Partial Public Class Editor

		'''<summary>
		'''pnlEditor control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlEditor As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''pnlTextbox control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlTextbox As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''txtValue control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtValue As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''pnlHtmlValue control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlHtmlValue As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''cmdSwitch control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdSwitch As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
